version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - .production.env
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d

  server:
    container_name: server
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .production.env
    depends_on:
      - postgres
    image: our_app_server